[tool.pytest.ini_options]
pythonpath = [
  ".",
  "src",
]

# Keep other potential configurations below if they exist
# For example:
# [tool.ruff]
# ... 

markers = [
    "integration: marks tests that require integration with external services",
]
asyncio_mode = "strict"