# SAFE 应急响应团队配置 v1.0 (基于 07_team_configuration_spec.md 规范)
version: "1.0"
team_name: safe-sop

# workflow_definition_file: "teams/safe-sop/workflow.yaml" # 不再使用单独文件

# 基于 docs.ref/chapter3.sop.e1.txt 的 SOP v8.1 更新 - 极简指令和任务目标描述
workflow:
  name: SAFE_SOP_v8.1_Declarative
  version: "2.1"
  description: "Standard Operating Procedure for SAFE Emergency Response, focusing on declarative task objectives."
  steps:
    - id: "sop_01_init_plan_prep"
      title: "SOP-01: 事件启动与规划准备"
      assignee: "Strategist" # Renamed from assignee_role
      description: | # Overall goal for this phase
        Establish the foundation for the response: log the event, ensure key information elements are complete, and set up the team configuration and overall plan structure.
      tasks:
        - task_id: "1.1"
          name: "Initial Event Logging"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: true
          description: "Log the initial incoming event information, creating a traceable record."
        - task_id: "1.2"
          name: "Key Element Check & Completion"
          assignee: "Awareness" # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Verify and complete the predefined set of key information elements based on the initial event record, identifying and filling gaps using available resources. Output a consolidated list."
        - task_id: "1.3"
          name: "Form Response Team & Plan SOP"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Determine required expert roles, configure the response team, and instantiate the overall Standard Operating Procedure (SOP) plan for this event."

    - id: "sop_02_sit_aware_risk_assess"
      title: "SOP-02: 态势理解与风险评估"
      assignee: "Awareness" # Renamed from assignee_role
      description: | # Overall goal for this phase
        Develop comprehensive situational awareness and perform risk assessment based on available information. This provides the intelligence foundation for subsequent planning.
      tasks:
        - task_id: "2.1"
          name: "Multi-Source Information Integration"
          assignee: "Awareness" # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Gather, process, and integrate information from multiple relevant sources to build a comprehensive dataset for situation analysis."
        - task_id: "2.2"
          name: "Comprehensive Situation Analysis"
          assignee: "Awareness" # Renamed from assignee_role
          is_atomic: true
          description: "Analyze the integrated information to understand the current situation, including scope, trends, impacts, and vulnerabilities. Output a structured situation analysis."
        - task_id: "2.3"
          name: "Comprehensive Risk Assessment"
          assignee: None # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Perform a comprehensive risk assessment. This involves an initial broad assessment, a potential decision point for specialized deep assessment by relevant experts, and integration of all findings into a final risk report."

    - id: "sop_03_objectives_coa_dev"
      title: "SOP-03: 目标确定与方案制定"
      assignee: "Strategist" # Renamed from assignee_role
      description: | # Overall goal for this phase
        Transition from analysis to action planning: define clear response objectives and develop the optimal Course of Action (CoA) to achieve them based on the assessed situation and risks.
      tasks:
        - task_id: "3.1"
          name: "Set Action Objectives & Priorities"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: true
          description: "Define specific, measurable, achievable, relevant, and time-bound (SMART) action objectives based on the situation and risk assessment. Prioritize these objectives."
        - task_id: "3.2"
          name: "Develop Course of Action (CoA)"
          assignee: None # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Develop a recommended Course of Action (CoA). This involves relevant experts generating potential CoA options based on objectives, followed by evaluation and selection of the most suitable CoA framework."

    - id: "sop_04_resource_plan_final"
      title: "SOP-04: 资源确认与计划定稿"
      assignee: "Strategist" # Renamed from assignee_role
      description: | # Overall goal for this phase
        Confirm the resource feasibility of the selected CoA and finalize the complete Emergency Response Plan, ready for execution or simulation.
      tasks:
        - task_id: "4.1"
          name: "Confirm Resources for Action Plan"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Verify the availability of resources required for the selected Course of Action by checking against current resource status. Identify confirmed resources and any gaps."
        - task_id: "4.2"
          name: "Finalize Emergency Response Plan"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: true
          description: "Consolidate the selected Course of Action and resource confirmation status into the final, actionable Emergency Response Plan."

    - id: "sop_05_ext_sim_exec"
      title: "SOP-05: (扩展) 行动方案模拟执行"
      assignee: "Executor" # Renamed from assignee_role
      description: | # Overall goal for this phase
        (Optional) Execute the finalized Emergency Response Plan within a simulated environment to validate its potential effectiveness and identify issues.
      tasks:
        - task_id: "5.1"
          name: "Drive Simulation based on Response Plan"
          assignee: "Executor" # Renamed from assignee_role
          is_atomic: false # Non-Atomic
          description: "Translate the finalized plan into simulation commands, configure and run the simulation in the Execution Validation Environment (EVE), and log the results."

    - id: "sop_06_ext_result_review"
      title: "SOP-06: (扩展) 结果检查与复盘"
      assignee: "Strategist" # Renamed from assignee_role
      description: | # Overall goal for this phase
        (Optional) Evaluate the results of the simulation execution and conduct a process review to capture lessons learned for future improvement.
      tasks:
        - task_id: "6.1"
          name: "Check Simulation Execution Results"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: true
          description: "Analyze the simulation execution logs, compare the outcomes against the plan's objectives, and report on the plan's performance in the simulation."
        - task_id: "6.2"
          name: "Conduct Process Review & Summary"
          assignee: "Strategist" # Renamed from assignee_role
          is_atomic: true
          description: "Conduct a review of the simulation results and the overall SOP execution process to identify lessons learned and potential improvements. Output a summary report."

global_settings:
  default_llm_config:
    model: "ds" # 可以根据需要调整默认模型
    temperature: 0.2
  shared_tools:
    # 假设 PlanManager 和 ArtifactManager 是所有角色都需要的基础工具
    # 注意：实际工具名称/类名需要与框架实现匹配
    # PlanManager 的工具由 PlanAgentTool 提供
    # ArtifactManager 的工具直接注册
    # - PlanManager # 由 PlanAgentTool 提供
    # - ArtifactManager # 分解为独立工具
    # - resource_checker # 示例共享工具
    # - information_retriever # 示例共享工具
    # - information_processor # 示例共享工具
    # - specialized_analyzer # 示例共享工具
    # - knowledge_base_retriever # 示例共享工具
    # - eve_driver # 示例共享工具
    # - plan_translator # 示例共享工具

agents:
  # --- Strategist ---
  - name: Strategist
    agent: SOPAgent
    actions:
      - Coordinate team effort based on the overall workflow plan.
      - Make strategic decisions (e.g., need for expertise, CoA selection).
      - Integrate information and results from other roles.
      - Ensure overall plan coherence and completion.
      - Manage workflow execution via PlanManager (implicitly).
    prompt: |
      You are the ${agent.name} of the SAFE team.
      Your role is to coordinate the team's effort to execute the assigned emergency response workflow.
      Leverage your planning, reasoning, integration, and decision-making capabilities to perform assigned tasks and guide the team towards successful completion of the overall goal.
      Default to using Chinese for generated content unless specified otherwise.
    handoffs:
      - target: Awareness
      - target: FieldExpert
      - target: Executor
    assigned_tools: []

  # --- Awareness ---
  - name: Awareness
    agent: SOPAgent
    actions:
      - Gather, process, and integrate information from multiple sources.
      - Verify and complete key information elements.
      - Perform comprehensive situation analysis.
      - Conduct initial (broad) risk assessments.
      - Generate relevant information assets (KeyElementList, SituationAnalysisReport, etc.).
    prompt: |
      You are ${agent.name} in the SAFE team.
      Your role is to build situational awareness and perform initial risk assessments.
      Leverage your capabilities in information gathering, processing, fusion, analysis, and preliminary risk identification to execute assigned tasks effectively.
      Default to using Chinese for generated content unless specified otherwise.
    handoffs:
      - target: Strategist
      - target: FieldExpert
    assigned_tools:
      - DuckDuckGoSearch.use_search

  # --- Field Expert ---
  - name: FieldExpert
    agent: SOPAgent
    actions:
      - Perform deep, domain-specific risk assessments based on expertise.
      - Generate detailed, domain-relevant Course of Action (CoA) options.
      - Provide specialized analysis and insights when requested.
    expertise_area: "Fire Safety and Suppression"
    prompt: |
      You are a ${agent.name} in the SAFE team, specializing in **${role_config.expertise_area}**.
      Your role is to provide deep domain-specific analysis and generate viable action options when assigned relevant tasks.
      Leverage your expertise in ${role_config.expertise_area} to execute assigned tasks, providing specialized insights and solutions.
      Default to using Chinese for generated content unless specified otherwise.
    handoffs:
      - target: Strategist
      - target: Awareness
    assigned_tools: []

  # --- Executor ---
  - name: Executor
    agent: SOPAgent
    actions:
      - Translate finalized response plans into executable simulation commands/configurations.
      - Interface with the Execution Validation Environment (EVE) to run simulations.
      - Monitor simulation execution and log results.
      - Report simulation outcomes.
    eve_interface_config:
      type: "StandardEVE_v1"
      endpoint: "http://localhost:8080/eve_api"
    prompt: |
      You are the ${agent.name} in the SAFE team.
      Your role is to interface with the Execution Validation Environment (EVE) to run simulations based on assigned tasks.
      Leverage your capability to translate plans and manage the simulation process using the configured EVE interface (${role_config.eve_interface_config.type}).
      Default to using Chinese for internal logging if applicable; EVE interaction format is dictated by the interface.
    handoffs:
      - target: Strategist
    assigned_tools: []

# --- 其他可能的全局配置 ---
# workflow_definition_file: "path/to/workflow.yaml" # 可选：指向单独的工作流文件
# message_bus_config: ... # 可选：消息总线配置 