# SAFE 应急响应团队配置 v1.0 (基于 07_team_configuration_spec.md 规范)
version: "1.0"
name: safe-sop
task: 2024年 7·5华容县洞庭湖决堤
# workflow_definition_file: "teams/safe-sop/workflow.yaml" # 不再使用单独文件

# 基于 docs.ref/chapter3.sop.e1.txt 的 SOP v8.1 更新 - 极简指令和任务目标描述
workflows:
- name: SAFE_SOP_v8.1_Declarative
  version: "2.1"
  description: "SAFE应急响应标准作业流程，聚焦于声明式任务目标。"
  steps:
    - id: "1"
      name: "Init Plan Prep"
      label: "事件启动与规划准备"
      assignee: "Strategist"
      description: |
        事件启动与规划准备：记录事件、核查关键信息、明确响应目标，为后续分工和计划执行打下基础。
      tasks:
        - id: "1"
          name: "Key Element Check & Completion"
          label: "关键信息核查与补全"
          assignee: "Awareness"
          description: "核查并补全事件相关的关键信息要素，确保信息完整，为后续响应提供依据。输出关键信息清单。"
        - id: "2"
          name: "Clarify Response Objectives"
          label: "明确响应目标"
          assignee: "Strategist"
          description: "根据已核查的关键信息，明确本次响应的主要目标和优先事项，为后续分工和计划制定提供方向。"

    - id: "2"
      name: "Situation Awareness & Risk Assessment"
      label: "态势理解与风险评估"
      assignee: "Awareness"
      description: |
        基于现有信息，建立全面的态势感知并进行风险评估，为后续规划提供情报基础。
      tasks:
        - id: "1"
          name: "Multi-Source Information Integration"
          label: "多源信息整合"
          assignee: "Awareness"
          description: "收集、处理并整合多渠道相关信息，形成用于态势分析的综合数据集。"
        - id: "2"
          name: "Comprehensive Situation Analysis"
          label: "综合态势分析"
          assignee: "Awareness"
          description: "分析整合后的信息，理解当前态势，包括范围、趋势、影响和脆弱点。输出结构化态势分析。"
        - id: "3"
          name: "Comprehensive Risk Assessment"
          label: "全面风险评估"
          assignee: "Awareness"
          description: "开展全面风险评估，包括初步广泛评估、如有需要由相关专家进行专项深度评估，并整合所有结论形成最终风险报告。"

    - id: "3"
      name: "Objectives & CoA Development"
      label: "目标确定与方案制定"
      assignee: "Strategist"
      description: |
        从分析过渡到行动规划：明确响应目标，并基于已评估的态势和风险制定最优行动方案（CoA）。
      tasks:
        - id: "1"
          name: "Set Action Objectives & Priorities"
          label: "制定行动目标与优先级"
          assignee: "Strategist"
          description: "根据态势和风险评估，制定具体、可衡量、可实现、相关且有时限（SMART）的行动目标，并进行优先级排序。"
        - id: "2"
          name: "Develop Course of Action (CoA)"
          label: "制定行动方案（CoA）"
          assignee: "FieldExpert"
          description: "制定推荐的行动方案（CoA），由相关专家基于目标生成可选CoA，经评估后选出最合适的CoA框架。"

    - id: "4"
      name: "Resource Confirmation & Plan Finalization"
      label: "资源确认与计划定稿"
      assignee: "Strategist"
      description: |
        确认所选CoA的资源可行性，定稿完整的应急响应计划，准备执行或仿真。
      tasks:
        - id: "1"
          name: "Confirm Resources for Action Plan"
          label: "确认行动方案所需资源"
          assignee: "Strategist"
          description: "核查所选行动方案所需资源的可用性，结合当前资源状况，明确已确认资源和存在的缺口。"
        - id: "2"
          name: "Finalize Emergency Response Plan"
          label: "定稿应急响应计划"
          assignee: "Strategist"
          description: "将所选行动方案与资源确认情况整合为最终可执行的应急响应计划。"

    - id: "5"
      name: "Simulation Execution"
      label: "行动方案模拟执行"
      assignee: "Executor"
      description: |
        在仿真环境中执行定稿的应急响应计划，验证其有效性并发现潜在问题。
      tasks:
        - id: "1"
          name: "Drive Simulation based on Response Plan"
          label: "基于响应计划驱动仿真"
          assignee: "Executor"
          description: "将定稿计划转化为仿真指令，在执行验证环境（EVE）中配置并运行仿真，记录结果。"

    - id: "6"
      name: "Result Review & Summary"
      label: "结果检查与复盘"
      assignee: "Strategist"
      description: |
        评估仿真执行结果，开展流程复盘，总结经验教训以便未来改进。
      tasks:
        - id: "1"
          name: "Check Simulation Execution Results"
          label: "检查仿真执行结果"
          assignee: "Strategist"
          description: "分析仿真执行日志，对比计划目标，报告仿真中的计划表现。"
        - id: "2"
          name: "Conduct Process Review & Summary"
          label: "复盘与总结"
          assignee: "Strategist"
          description: "复盘仿真结果及整体SOP执行过程，总结经验教训和改进点，输出总结报告。"

global_settings:
  default_llm_config:
    model: "ds" # 可以根据需要调整默认模型
    temperature: 0.2

agents:
  # --- Strategist ---
  - name: Strategist
    actions:
      - 协调团队根据整体工作流计划开展工作。
      - 做出战略决策（如是否需要专家、CoA选择等）。
      - 整合其他角色的信息和结果。
      - 确保整体计划的连贯性和完成。
    prompt: |
      你的职责是协调团队执行分配的应急响应工作流。
      利用你的规划、推理、整合和决策能力完成分配任务，引导团队实现整体目标。
      除非特别说明，生成内容默认使用中文。

  # --- Awareness ---
  - name: Awareness
    actions:
      - 收集、处理并整合多渠道信息。
      - 核查并补全关键信息要素。
      - 进行全面的态势分析。
      - 开展初步（广泛）风险评估。
      - 生成相关信息资产（关键信息清单、态势分析报告等）。
    prompt: |
      你的职责是建立态势感知并进行初步风险评估。
      利用你在信息收集、处理、融合、分析和初步风险识别方面的能力，高效完成分配任务。
      除非特别说明，生成内容默认使用中文。

  # --- Field Expert ---
  - name: FieldExpert
    actions:
      - 提供专项分析和洞见（按需）/ Provide specialized analysis and insights when requested.
    prompt: |
      你的职责是在分配相关任务时，提供深度领域分析并生成可行的行动方案。
      利用你在${role_config.expertise_area}的专业能力，完成分配任务，输出专业见解和解决方案。
      除非特别说明，生成内容默认使用中文。

  # --- Executor ---
  - name: Executor
    actions:
      - 将最终响应计划转化为可执行的仿真指令/配置。
      - 对接执行验证环境（EVE）运行仿真。
      - 监控仿真执行并记录结果。
      - 汇报仿真结果。
    prompt: |
      你的职责是对接执行验证环境（EVE），根据分配任务运行仿真。
      利用你将计划转化并管理仿真流程的能力，结合配置的EVE接口（${role_config.eve_interface_config.type}）完成任务。
      如适用，内部日志默认使用中文；EVE交互格式由接口决定。

# --- 其他可能的全局配置 ---
# workflow_definition_file: "path/to/workflow.yaml" # 可选：指向单独的工作流文件
# message_bus_config: ... # 可选：消息总线配置 